site_name: Ro-Express
site_author: HawDevelopment
site_description: >-
  One of the best Modules for clearing up networking complexity. It has a syntax like expressjs.
  Its not only better but also has a lot of features such as: Middleware, Diffrent Methods, Paths and Responses.

repo_name: HawDevelopment/Ro-Express
repo_url: https://github.com/HawDevelopment/Ro-Express
edit_uri: ""

copyright: Copyright &copy; 2021 - 2022 HawDevelopment

nav:
  - Home: index.md
  - Installation: Installation.md
  - Getting Started: Getting_Started.md
  - Examples: Example.md
  - Api: Api.md

theme:
  features:
    - navigation.instant
  font:
    text: Ubuntu
    code: Roboto Mono
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/HawDevelopment/Ro-Express
      name: GitHub repo
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/HawDevelopment
      name: HawDevelopment's Twitter

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed